language: bash

sudo: required

services:
  - docker

addons:
  hosts:
    - ecag-fixml-dev1

install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo add-apt-repository ppa:qpid/released --yes
  - sudo apt-get update -q
  - sudo apt-get install -q libsasl2-2 libsasl2-modules libsasl2-modules-db bats qpid-send qpid-receive

script:
  - bats tests.bats
